#ifndef INTERRUPT_H
#define INTERRUPT_H

#define REMAPPED_RESET_VECTOR_ADDRESS			0x1200
#define REMAPPED_HIGH_INTERRUPT_VECTOR_ADDRESS	0x1208
#define REMAPPED_LOW_INTERRUPT_VECTOR_ADDRESS	0x1218

#endif




